version: '2.1'
services:
    ###################
    ##    BACKEND    ##
    ###################

    xotomicro-back-event-service:
        build:
            context: .
            dockerfile: docker/dockerfile.production
        container_name: xotomicro-back-event-service
        image: xotomicro-back-event-service
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - JVM_OPTS=-Xmx512m -Xms512m
            - PROFILE=${PROFILE}
            - ENV=${ENV}

        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8085/actuator/health']
            interval: 10s
            timeout: 1s
            retries: 10
        env_file:
            - .env
