server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    preferIpAddress: true

kafka:
  bootstrapServer: kafka-headless:9092
  consumerGroup: xotomicro-back-event-service
  topics: product

spring:
  application:
    name: xotomicro-back-event-service

elasticsearch:
  # elasticsearch-master-hl:
  host: elasticsearch:9200
  # host: elasticsearch-master-hl:9200
